# Generated by Django 6.0.6 on 2026-09-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0002_registrationevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshare',
            name='role',
            field=models.CharField(choices=[('writer', 'Writer'), ('composer', 'Composer'), ('writer_composer', 'Writer/Composer'), ('publisher', 'Publisher'), ('admin', 'Admin publisher')], default='writer', max_length=16),
        ),
    ]
