# Generated by Django 6.0.6 on 2026-09-25 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_track_iswc'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('primary', 'Primary Artist'), ('featured', 'Featured Artist')], default='primary', max_length=16)),
                ('billing_order', models.PositiveSmallIntegerField(default=1)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='track_credits', to='catalog.artist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='catalog.track')),
            ],
            options={
                'ordering': ('billing_order',),
                'constraints': [models.UniqueConstraint(fields=('track', 'artist'), name='unique_artist_per_track')],
            },
        ),
    ]
