# Generated by Django 6.0.6 on 2026-09-30 18:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_trackartist'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier_type', models.CharField(choices=[('isrc', 'ISRC')], default='isrc', max_length=16)),
                ('value', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^[A-Z]{2}[A-Z0-9]{3}[0-9]{7}$', 'Enter a valid ISRC.')])),
                ('asset_kind', models.CharField(choices=[('audio', 'Audio'), ('music_video', 'Music video'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_identifiers', to='catalog.label')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='catalog.track')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('label', 'identifier_type', 'value'), name='unique_track_identifier_per_label')],
            },
        ),
    ]
