# Generated by Django 6.0.6 on 2026-09-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalties', '0003_royaltyrun_consolidation_error_royaltyrunpayout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='royaltystatement',
            name='distributor',
            field=models.CharField(choices=[('distrokid', 'DistroKid'), ('tunecore', 'TuneCore'), ('cd_baby', 'CD Baby'), ('symphonic', 'Symphonic'), ('onerpm', 'ONErpm'), ('routenote', 'RouteNote'), ('toolost', 'TooLost'), ('fuga', 'FUGA'), ('vydia', 'Vydia'), ('the_orchard', 'The Orchard'), ('colonize', 'Colonize Media'), ('lujo', 'Lujo Network'), ('other', 'Other')], max_length=32),
        ),
    ]
