# Generated by Django 6.0.6 on 2026-09-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalties', '0004_alter_royaltystatement_distributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='royaltylineitem',
            name='source_asset_kind',
            field=models.CharField(choices=[('audio', 'Audio'), ('music_video', 'Music video'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', help_text='Asset classification captured when this line was imported.', max_length=16),
        ),
    ]
